services:
  react-app:
    container_name: prime
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./tarefas:/app
    working_dir: /app
    command: >
      sh -c "if [ ! -f package.json ]; then
              npm create vite@latest . -- --template react &&
              npm install react-router-dom axios &&
              npm install firebase &&
              npm install react-toastify
            else
              npm install
            fi &&
            npm run dev -- --host 0.0.0.0"

    # command: >
    #   sh -c "if [ ! -f package.json ]; then
    #            npm create vite@latest . -- --template react &&
    #            npm install react-router-dom axios;
    #            npm install firebase;
    #            npm install react-toastify;
    #          else
    #            npm install;
    #          fi &&
    #          npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
